export const FILE_DELETE_REQUEST = "FILE_DELETE_REQUEST"
export const FILE_DELETE_SUCCESS = "FILE_DELETE_SUCCESS"
export const FILE_DELETE_FAIL = "FILE_DELETE_FAIL"

export const FILE_GET_REQUEST = "FILE_GET_REQUEST"
export const FILE_GET_SUCCESS = "FILE_GET_SUCCESS"
export const FILE_GET_FAIL = "FILE_GET_FAIL"

export const FILE_CREATE_REQUEST = "FILE_CREATE_REQUEST"
export const FILE_CREATE_SUCCESS = "FILE_CREATE_SUCCESS"
export const FILE_CREATE_FAIL = "FILE_CREATE_FAIL"
export const FILE_CREATE_RESET = "FILE_CREATE_RESET"
